#COMPOSE SCREENS

version: "2"
services:
  #####################################################################################################
  cms:
    image: jonimoas/erdbms:0.1
    container_name: erdbms
    restart: always
    environment:
      PORT: 2380
      EXT_PORT: 80
    ports:
      - "2380:80"
  #####################################################################################################
